Fix deprecation warning for `Order#update!`
solidusio-contrib/solidus_active_shipping pull request #47
Opened 2017-09-18 23:10 UTC by swcraig

Solidus wants us to use `Order#recalculate` instead.

Deprecation notice:
https://github.com/solidusio/solidus/blob/1c0d0bbbdd9f11391698d24dbcfd181300d07ff5/core/app/models/spree/order.rb#L253-L260

2017-09-19 04:56 UTC, tvdeyen requested changes
Without a version check this will fail for older versions of Solidus.

2017-09-19 17:12 UTC, forkata commented
@tvdeyen Is right, we can't do this without checking the solidus gem version.

2017-09-20 17:33 UTC, swcraig commented
Gah! Of course. One day I will remember to always consider backwards compatibility. I will work on something for this.

2017-09-21 21:39 UTC, swcraig commented
I believe this is good to go now.

2017-09-22 04:54 UTC, tvdeyen approved these changes
Thanks

2017-09-22 20:08 UTC, merged