Add minor fixes
solidusio-contrib/solidus_active_shipping pull request #49
Opened 2018-01-04 21:26 UTC by jtapia

2018-01-04 22:13 UTC, dangerdogz commented
Thanks for the contribution,

My first suggestion would be to add a more descriptive commit message & split the changes into smaller commits if applicable

Will review the individual changes as soon as possible

2018-01-05 01:34 UTC, jtapia commented
@dangerdogz what do you think?

2018-01-11 19:40 UTC, dangerdogz commented
The 2.X releases include several breaking changes that we need to look into and the test suite is unstable on master. Can you extract the ActiveShipping changes as a separate PR? The remaining changes are much more straightforward and I can look into the build failures in the meantime

2018-01-15 04:39 UTC, jtapia commented
@dangerdogz done

2018-01-17 00:11 UTC, fredericboivin requested changes
The changes to `active_shipping_settings/edit` breaks the extension for every version of Solidus prior to 2.4.0 as this is when the `preference_fields` partial were introduced

2018-01-17 00:11 UTC, fredericboivin commented on Gemfile
> +  gem 'byebug'
Why is this dependency needed? This can be easily added in the host application if needed

2018-01-18 17:33 UTC, jtapia commented
@dangerdogz removed

2018-01-18 17:58 UTC, jtapia commented
@dangerdogz for the `active_shipping_settings/edit` issue I sent this https://github.com/solidusio-contrib/solidus_active_shipping/pull/49/commits/beffaace8cf4ed198242659cd867f8b5fbad8e06

2018-02-07 02:29 UTC, dangerdogz commented
Considering the status of this extension, I don't think the value added by the new partials warrants the maintenance burden of having to support different views for different versions.

I would be happy to merge the other commits otherwise 👍

2018-02-09 17:33 UTC, jtapia commented
@dangerdogz I removed the latest commit with the view changes, let me know if you think that I need to do anything else here, thanks

2018-02-28 22:07 UTC, merged